DROP TABLE IF EXISTS `apple`;

CREATE TABLE IF NOT EXISTS `apple` (
    `id` int NOT NULL AUTO_INCREMENT,
    `color` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;