server:
  port: 8084

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# spring jdbc datasource config
spring:
  application:
    name: test
  h2:
    console:
      path: /h2-console
      enabled: true
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/t1?useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root@123
#    hikari:
#      pool-name: Hikari-test
#      maximum-pool-size: 60
#      minimum-idle: 10


my:
  test: test